// Generated by CoffeeScript 1.7.1
this.BoardState = (function() {
  function _Class(grid) {
    this.grid = grid;
  }

  _Class.prototype.cell = function(row, col) {
    var c;
    c = this.grid.cells[row - 1][col - 1];
    if (!c) {
      return null;
    }
    return c.value;
  };

  return _Class;

})();
