// Generated by CoffeeScript 1.7.1
var Bot;

Bot = (function() {
  function Bot(grid) {
    this.grid = grid;
    console.log(this.grid);
  }

  Bot.prototype.expectimax = function(boardState, depth, ourTurn) {
    var childScores;
    if (depth === 0) {
      return this.evaluate(boardState);
    }
    if (ourTurn) {
      childScores = boardState.legalMoves().map(function(move) {
        return this.expectimax(boardState.move(move), depth - 1, false);
      });
      return Math.max.apply(Math, childScores);
    }
  };

  Bot.prototype.getBestMove = function() {
    return '1';
  };

  return Bot;

})();
