// Generated by CoffeeScript 1.7.1
var Bot;

Bot = (function() {
  function Bot(grid) {
    this.grid = grid;
    console.log(this.grid);
  }

  Bot.prototype.getBestMove = function() {
    return '1';
  };

  return Bot;

})();
