// Generated by CoffeeScript 1.7.1
(function() {
  window.Bot = (function() {
    function _Class(grid) {
      this.grid = grid;
    }

    _Class.prototype.getBestMove = function() {
      return '1';
    };

    return _Class;

  })();

}).call(this);
